### ISSUE TITLE
Add postgresql-contrib as dependency

### ISSUE THREAD

**Issue by fpuga** [Emapic/emapic#1]
I have an issue deploying the db with sqitch

```
ERROR:  could not open extension control file "/usr/share/postgresql/9.3/extension/unaccent.control": No such file or directory
```

It was because i dont' have `postgresql-contrib-9.3` (i was using postgres 9.3) installed on my virtual machine. Maybe is a good idea add it as a pre-requisite

**Comment by jorgelf** [comment]
Yeah, my mistake, should have tested it on a 100% clean system in order to identify these minor requirements.
I'll point out this requirement in the readme and tell how to remove it in case the user doesn't need it in its installation.
